# -*- mode: yaml; fill-column: 80 -*-
---

position:
  latitude: 30.156
  longitude: 118.657            # Jixixian

zoom: 5

images:
  - image: images/lovestory/hunsha/01.jpg
    date: 2008/03
    latitude: 30.156
    longitude: 118.657
    description: 他在丛中笑

  - image: images/lovestory/hunsha/02.jpg
    date: 2014/04
    latitude: 39.991
    longitude: 116.309
    description: 她在丛中笑

  - image: images/lovestory/hunsha/03.jpg
    date: 2009/03
    latitude: 18.255
    longitude: 109.540
    description: 她在海南岛

  - image: images/lovestory/hunsha/04.jpg
    date: 2014/04
    latitude: 39.991
    longitude: 116.309
    description: 她在穿白纱

  - image: images/lovestory/hunsha/05.jpg
    date: 2010/03
    latitude: 30.209
    longitude: 120.135
    description: 他在虎跑泉

  - image: images/lovestory/hunsha/06.jpg
    date: 2014/04
    latitude: 39.991
    longitude: 116.309
    description: 他在手捧花

  - image: images/lovestory/hunsha/07.jpg
    date: 2012/01
    latitude: 45.770
    longitude: 126.627
    description: 她在哈尔滨

  - image: images/lovestory/hunsha/08.jpg
    date: 2014/04
    latitude: 39.991
    longitude: 116.309
    description: 她在捏他脸

  - image: images/lovestory/hunsha/09.jpg
    date: 2012/10
    latitude: 40.603
    longitude: 117.440
    description: 他在雾灵山

  - image: images/lovestory/hunsha/10.jpg
    date: 2014/04
    latitude: 39.991
    longitude: 116.309
    description: 她在弄长裙

  - image: images/lovestory/hunsha/11.jpg
    date: 2012/01
    latitude: 30.960
    longitude: 101.745
    description: 她在川康地

  - image: images/lovestory/hunsha/12.jpg
    date: 2014/04
    latitude: 39.991
    longitude: 116.309
    description: 他在未名湖

story:
  - 韶华易逝
  - 转瞬间
  - 他和她
  - 两个傻孩子
  - 已经牵手走过了六年多的岁月
  - 相识
  - 相恋
  - 相爱
  - 相知
  - 相守
  - 相伴
  - 相行
