# -*- mode: yaml; fill-column: 80 -*-
---

position:
  latitude: 30.673
  longitude: 104.061            # chengdu

zoom: 5

images:
  - image: images/lovestory/xizang/01.jpg
    date: 2008/08
    latitude: 30.673
    longitude: 104.061
    description: 成都武侯祠

  - image: images/lovestory/xizang/02.jpg
    date: 2008/08
    latitude: 30.673
    longitude: 104.061
    description: 牵手在路上，小子笑羞羞

  - image: images/lovestory/xizang/03.jpg
    date: 2008/08
    latitude: 31.622
    longitude: 99.878
    description: 川康大地

  - image: images/lovestory/xizang/04.jpg
    date: 2008/08
    latitude: 31.834
    longitude: 99.379
    description: 高原平湖

  - image: images/lovestory/xizang/05.jpg
    date: 2008/08
    latitude: 31.955
    longitude: 98.749
    description: 雀儿山高

  - image: images/lovestory/xizang/06.jpg
    date: 2008/08
    latitude: 31.620
    longitude: 98.583
    description: 山口彩虹

  - image: images/lovestory/xizang/07.jpg
    date: 2008/08
    latitude: 33.701
    longitude: 92.121
    description: 三江源头

  - image: images/lovestory/xizang/08.jpg
    date: 2008/08
    latitude: 30.271
    longitude: 120.195
    description: 翘首企盼

story:
  - 后来他去了西藏
  - 318国道
  - 中国人的景观大道
  - 他想用车轮
  - 在祖国的大地上
  - 留下一道汗水的痕迹
  - 他
  - 风雨兼程
  - 她
  - 翘首企盼
