# -*- mode: yaml; fill-column: 80 -*-
---

position:
  latitude: 29.154
  longitude: 120.996

zoom: 13

images:
  - image: images/lovestory/tiantai/01.jpg
    date: 1988/10
    latitude: 29.154
    longitude: 120.996
    description: 胖乎乎

  - image: images/lovestory/tiantai/02.jpg
    date: 1993/08
    latitude: 29.154
    longitude: 120.996
    description: 傻呵呵

  - image: images/lovestory/tiantai/03.jpg
    date: 2006/07
    latitude: 29.154
    longitude: 120.996
    description: 大一新生，只是少女初成

story:
  - 另一个也成长在大山里
  - 傻里傻气
  - 18岁之前从未出过浙江
  - 没有看过大海
  - 她可以画下漂亮的工笔素描
  - 却不会在电脑上发送邮件
