# -*- mode: yaml; fill-column: 80 -*-
---

position:
  latitude: 32.523
  longitude: 110.979            # Shiyan City

zoom: 9

images:
  - image: images/lovestory/shennongjia/01.jpg
    date: 2009/05
    latitude: 30.308
    longitude: 120.085
    description: 向着夕阳

  - image: images/lovestory/shennongjia/02.jpg
    date: 2009/05
    latitude: 30.308
    longitude: 120.085
    description: 风雨兼程

  - image: images/lovestory/shennongjia/03.jpg
    date: 2009/05
    latitude: 32.099
    longitude: 110.730
    description: 哪怕一路泥泞

  - image: images/lovestory/shennongjia/04.jpg
    date: 2009/05
    latitude: 32.023
    longitude: 110.716
    description: 晒晒太阳

  - image: images/lovestory/shennongjia/05.jpg
    date: 2009/05
    latitude: 31.931
    longitude: 110.746
    description: 一路颠簸

  - image: images/lovestory/shennongjia/06.jpg
    date: 2009/05
    latitude: 31.807
    longitude: 110.509
    description: 相伴而行

  - image: images/lovestory/shennongjia/07.jpg
    date: 2009/05
    latitude: 31.569
    longitude: 110.362
    description: 总算碰上个好天气

  - image: images/lovestory/shennongjia/08.jpg
    date: 2009/05
    latitude: 31.445
    longitude: 110.431
    description: 笑容灿烂

  - image: images/lovestory/shennongjia/09.jpg
    date: 2009/05
    latitude: 31.336
    longitude: 110.661
    description: 怎么哭了

  - image: images/lovestory/shennongjia/10.jpg
    date: 2009/05
    latitude: 30.687
    longitude: 111.236
    description: 还是累了

story:
  - 他们一起去神农架
  - 一路泥泞
  - 一路颠簸
  - 一路风雨
  - 一路相伴
  - 他觉得
  - 要珍惜这个不俱风雨勇往前行的妞
  - 她觉得
  - 有他在
  - 我不会迷路
  - 嗯
