# -*- mode: yaml; fill-column: 80 -*-
---

position:
  latitude: 28.855
  longitude: 120.754

images:
  - image: images/lovestory/zhedong/01.jpg
    date: 2007/10
    latitude: 28.855
    longitude: 120.754
    description: 浙东骑行

  - image: images/lovestory/zhedong/02.jpg
    date: 2007/10
    latitude: 28.855
    longitude: 120.754
    description: 浙东骑行

story:
  - 他们相识在旅行途中
  - 青春年少
  - 懵懂悸动
